### PR TITLE
Produce .dSYM for each frameworks inside the xcframework

### PR DESCRIPTION
**Pull request by spouliot**

### CODE REVIEW

**Comment by sbooth** [comment]
Is there a reason to prefer `` `pwd` `` over the make-provided `S(CURDIR)`?

```
xcodebuild -create-xcframework $(foreach xcarchive,$^,-framework "$(xcarchive)/Products/Library/Frameworks/$(FRAMEWORK_NAME).framework" -debug-symbols "$(CURDIR)/$(xcarchive)/dSYMs/$(FRAMEWORK_NAME).framework.dSYM" ) -output "$@"
```

**Comment by spouliot** [comment]
Not really. I just adapted this from a script I used.
The only important piece is that the full path is required, so a relative one would not work.

**Comment by sbooth** [comment]
Interestingly it seems `CURDIR` won't work as expected for invocations using `make -f`. In those cases the subdirectory `include` would fail since `..` will refer to the parent dir where `make` was invoked.

**Comment by sbooth** [comment]
I incorporated an equivalent change using `realpath` in 8f30f6f. Thanks for suggesting this!

**Pull request closed without merging**
